### ISSUE TITLE
Release this to Clojars :)

### ISSUE THREAD

**Issue by alexandergunnarson** [dco-dev/interval-tree#2]
Hey @dco-lentz! Been a while since I mentioned you on GitHub :) Do you think you could release this to Clojars? One current use case I have for it is doing rate limiting. I'm sure there are other future uses I'll have for it.

Thanks so much and all the best!

**Comment by danlentz** [comment]
Hey Alex — that’s the plan.   I’m not super happy with the current artifact
names and maybe some other structure of the repo.   Any interest in doing a
code review and offering any suggestions you can think of?   BTW, I’d be
really happy if it can be useful to your project ☺️

Best,
Dan

**Comment by alexandergunnarson** [comment]
I'd be honored to do a code review! ☺️ I'll be able to possibly later today — if not, then likely tomorrow. Also, where did those tests and performance evaluations go? I think they were there at one point but I may be hallucinating.

In the meantime, do you feel comfortable with me releasing this to Clojars as `[quantum/com-dean-clojure-interval-tree "0.1"]` ? If not, that's totally fine — I might just put the contents of `src` in my `src` folder temporarily.

**Comment by alexandergunnarson** [comment]
In fact, how about I just use a different interval tree library till you release to Clojars. That way your work isn’t prefixed in a confusing way to whatever random artifact consumer stops by Clojars, and I don’t accidentally commit any of this to Quantum or other projects I’m working on. The very last thing I want to do is take away credit from you!

**Comment by dco-lentz** [comment]
Finally getting some time here: https://github.com/dco-dev/interval-tree/pull/6

**Comment by alexandergunnarson** [comment]
Nice! Will look!

**Comment by dco-lentz** [comment]
Done! https://clojars.org/com.dean/interval-tree

**Comment by alexandergunnarson** [comment]
Exciting times! Thanks so much! 😃
